import { createHash } from 'node:crypto';

function stable(v){if(Array.isArray(v))return'['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v);}
function id(prefix,seed){return prefix+'_'+createHash('sha256').update(stable(seed)).digest('hex').slice(0,20);}
export function entity(input){return{id:input.id||id('ent',input),type:input.type,name:input.name??null,identifiers:input.identifiers||{},geometry:input.geometry??null,atlas_address:input.atlas_address??null,scope:input.scope??null,properties:input.properties||{},derived_from:[...new Set(input.derived_from||[])]};}
export function relation(input){return{id:input.id||id('rel',{subject:input.subject,predicate:input.predicate,object:input.object,evidence:input.derived_from||[]}),subject:input.subject,predicate:input.predicate,object:input.object,value:input.value??null,valid_from:input.valid_from??null,valid_to:input.valid_to??null,epistemic:input.epistemic||'DERIVED',derived_from:[...new Set(input.derived_from||[])],provenance:input.provenance||{}};}
function pushEntity(map,e){const old=map.get(e.id);if(!old)map.set(e.id,e);else{old.derived_from=[...new Set([...old.derived_from,...e.derived_from])];if(!old.name&&e.name)old.name=e.name;if(!old.atlas_address&&e.atlas_address)old.atlas_address=e.atlas_address;}return e.id;}

export function buildGraph(signals){
 const entities=new Map(),relations=[];
 for(const s of signals){const v=s.value||{};
  if(s.source==='fdic-locations'||s.source==='fdic-sod'){
   const cert=v.cert==null?null:String(v.cert),branch=v.branch_id==null?null:String(v.branch_id);if(cert){const bankId=`fdic:${cert}`;pushEntity(entities,entity({id:bankId,type:'financial_institution',name:v.institution_name||null,identifiers:{fdic_cert:cert},derived_from:[s.id]}));if(branch){const brId=`fdic-branch:${cert}:${branch}`;pushEntity(entities,entity({id:brId,type:'bank_branch',name:v.branch_name||null,identifiers:{fdic_cert:cert,branch_id:branch},geometry:s.geometry,atlas_address:s.atlas_address,derived_from:[s.id]}));relations.push(relation({subject:brId,predicate:'branch_of',object:bankId,epistemic:'REPORTED',derived_from:[s.id]}));if(Number.isFinite(+v.deposits_usd))relations.push(relation({subject:brId,predicate:'holds_reported_deposits',object:bankId,value:{amount_usd:+v.deposits_usd},epistemic:'REPORTED',valid_from:s.valid_from,derived_from:[s.id]}));}}
  }
  if(s.source==='hmda-lenders'&&v.lei){const lei=String(v.lei),entId=`lei:${lei}`,scopeId=`census-county:${v.county_geoid}`;pushEntity(entities,entity({id:entId,type:'legal_entity',name:v.name||null,identifiers:{lei},derived_from:[s.id]}));pushEntity(entities,entity({id:scopeId,type:'administrative_scope',name:v.county_name||null,identifiers:{census_geoid:v.county_geoid},scope:'county',properties:{state:v.state||null},derived_from:[s.id]}));relations.push(relation({subject:entId,predicate:'reports_hmda_activity_in',object:scopeId,value:{year:v.year},epistemic:'REPORTED',derived_from:[s.id]}));}
  if(s.source==='usaspending-county'&&v.county_geoid){const scopeId=`census-county:${v.county_geoid}`,gov='institution:us-federal-government';pushEntity(entities,entity({id:scopeId,type:'administrative_scope',name:v.county||null,identifiers:{census_geoid:v.county_geoid},scope:'county',properties:{state:v.state||null},derived_from:[s.id]}));pushEntity(entities,entity({id:gov,type:'institution',name:'United States federal government',derived_from:[s.id]}));const amount=Number(v.amount_usd);relations.push(relation({subject:gov,predicate:'reports_obligations_with_place_of_performance',object:scopeId,value:{amount_usd:Number.isFinite(amount)?amount:null},epistemic:'REPORTED',derived_from:[s.id],provenance:{source:'USAspending',scope:'place_of_performance'}}));}
  if(s.source==='gleif-entity'&&v.lei){const entId=`lei:${v.lei}`;pushEntity(entities,entity({id:entId,type:'legal_entity',name:v.legal_name||null,identifiers:{lei:v.lei},properties:{jurisdiction:v.jurisdiction||null,entity_status:v.entity_status||null},derived_from:[s.id]}));}
  if(s.source==='gleif-parent'&&v.child_lei&&v.parent_lei){const child=`lei:${v.child_lei}`,parent=`lei:${v.parent_lei}`;pushEntity(entities,entity({id:child,type:'legal_entity',identifiers:{lei:v.child_lei},derived_from:[s.id]}));pushEntity(entities,entity({id:parent,type:'legal_entity',name:v.parent_name||null,identifiers:{lei:v.parent_lei},properties:{jurisdiction:v.parent_jurisdiction||null},derived_from:[s.id]}));relations.push(relation({subject:child,predicate:v.level==='ultimate'?'ultimately_consolidated_by':'directly_consolidated_by',object:parent,epistemic:'REPORTED',derived_from:[s.id],provenance:{standard:'GLEIF Level 2 accounting consolidation'}}));}
 }
 return{entities:[...entities.values()].sort((a,b)=>a.id.localeCompare(b.id)),relations:relations.sort((a,b)=>a.id.localeCompare(b.id))};
}
